In [129]:
# transform the text data tp feature vectors that can be used as input to the logistic regression
feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True,max_features=500, binary = True, ngram_range=(1,1))

X_train_features = feature_extraction.fit_transform(X_train)

# .transform used for data leakage
X_test_features = feature_extraction.transform(X_test)

# Convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [130]:
print(X_train_features.toarray())

[[0.         0.         0.35792324 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [131]:
#model = LogisticRegression()
#model.fit(X_train_features,Y_train)

In [132]:
model = SVC(kernel='rbf', C=1.0, random_state=42, probability=True)

# Train the model on the scaled training data (X_train_scaled, y_train)
# The model finds the optimal hyperplane to separate Diagnosis=0 and Diagnosis=1
model.fit(X_train_features, Y_train)

SVC(probability=True, random_state=42)

In [133]:
# prediction on training data

prediction_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train,prediction_on_training_data)

In [134]:
print('Accuracy on training data: ',accuracy_on_training_data)

Accuracy on training data:  0.9937177473636976


In [135]:
# prediction on testing data

prediction_on_testing_data = model.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test, prediction_on_testing_data)

In [136]:
print('Accuracy on training data: ',accuracy_on_testing_data)

Accuracy on training data:  0.9820627802690582


In [137]:
print(confusion_matrix(Y_test,prediction_on_testing_data))

[[965   1]
 [ 19 130]]


In [138]:
recall_score(Y_test,prediction_on_testing_data)

0.87248322147651

In [139]:
f1_score(Y_test,prediction_on_testing_data)

0.9285714285714286

In [140]:
precision_score(Y_test,prediction_on_testing_data)

0.9923664122137404

In [141]:
input_mail = ['you won some price money please share your account number for the transaction']

# convert text to feature vectors
input_data_features = feature_extraction.transform(input_mail)

# making prediction

prediction = model.predict(input_data_features)
print(prediction)

if(prediction[0]==1):
    print('Ham mail')

else:
    print('Spam mail')

[0]
Spam mail


In [142]:
input_mail1 = ['time want come']

# convert text to feature vectors
input_data_features1 = feature_extraction.transform(input_mail1)

# making prediction

prediction1 = model.predict(input_data_features1)
print(prediction1)

if(prediction[0]==1):
    print('Ham mail')

else:
    print('Spam mail')

[0]
Spam mail


In [143]:
input_mail2 = ['The meeting is scheduled for tommorow at 10 AM. ']

# convert text to feature vectors
input_data_features2 = feature_extraction.transform(input_mail2)

# making prediction

prediction2 = model.predict(input_data_features2)
print(prediction2)

if(prediction[0]==1):
    print('Ham mail')

else:
    print('Spam mail')

[0]
Spam mail


In [225]:
cv = CountVectorizer (min_df=1, stop_words='english', ngram_range=(2,2),max_features=200, binary = True)
#feature_extraction = TfidfVectorizer(min_df=1, stop_words='english', lowercase=True,max_features=500, binary = True, ngram_range=(1,1))

In [226]:
X = cv.fit_transform(corpus).toarray()

In [227]:
X_train_features = cv.fit_transform(X_train)

# .transform used for data leakage
X_test_features = cv.transform(X_test)

# Convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [228]:
print(X_train_features.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [229]:
model = LogisticRegression()
model.fit(X_train_features,Y_train)

LogisticRegression()

In [230]:
# prediction on training data

prediction_on_training_data = model.predict(X_train_features)
accuracy_on_training_data = accuracy_score(Y_train,prediction_on_training_data)

In [231]:
print('Accuracy on training data: ',accuracy_on_training_data)

Accuracy on training data:  0.9360556428090644


In [232]:
# prediction on testing data

prediction_on_testing_data = model.predict(X_test_features)
accuracy_on_testing_data = accuracy_score(Y_test, prediction_on_testing_data)

In [233]:
print('Accuracy on training data: ',accuracy_on_testing_data)

Accuracy on training data:  0.9345291479820628


In [234]:
print(confusion_matrix(Y_test,prediction_on_testing_data))

[[965   1]
 [ 72  77]]


In [235]:
recall_score(Y_test,prediction_on_testing_data)

0.5167785234899329

In [236]:
precision_score(Y_test,prediction_on_testing_data)

0.9871794871794872

In [237]:
f1_score(Y_test,prediction_on_testing_data)

0.6784140969162996

In [238]:
input_mail = ['you won some price money please share your account number for the transaction']

# convert text to feature vectors
input_data_features = cv.transform(input_mail)

# making prediction

prediction = model.predict(input_data_features)
print(prediction)

if(prediction[0]==1):
    print('Ham mail')

else:
    print('Spam mail')

[0]
Spam mail


In [239]:
input_mail1 = ['time want come']

# convert text to feature vectors
input_data_features1 = cv.transform(input_mail1)

# making prediction

prediction1 = model.predict(input_data_features1)
print(prediction1)

if(prediction[0]==1):
    print('Ham mail')

else:
    print('Spam mail')

[0]
Spam mail


In [240]:
input_mail2 = ['The meeting is scheduled for tommorow at 10 AM. ']

# convert text to feature vectors
input_data_features2 = cv.transform(input_mail2)

# making prediction

prediction2 = model.predict(input_data_features2)
print(prediction2)

if(prediction[0]==1):
    print('Ham mail')

else:
    print('Spam mail')

[0]
Spam mail


In [43]:
import gensim
from gensim.models import Word2Vec, KeyedVectors
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['spam']

In [ ]:
wv.most_similar('cricket')

In [ ]:
wv.similarity("hockey","sports")

In [1]:
import pandas as pd
import numpy as np

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression

#nltk.download('punkt')
#nltk.download('stopwords')

In [2]:
df = pd.read_csv("Data/mail_data.csv") 

In [3]:
df['Category'] = df['Category'].map({'ham':0, 'spam':1})

x = df['Message']
y = df['Category']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42
)

In [272]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(
    stop_words='english',
    max_features=3000
)

X_train_bow = bow.fit_transform(X_train)
X_test_bow = bow.transform(X_test)

In [273]:
model_bow = LogisticRegression(max_iter=1000)
model_bow.fit(X_train_bow, y_train)

LogisticRegression(max_iter=1000)

In [274]:
y_pred_bow = model_bow.predict(X_test_bow)

print("BoW Accuracy:", accuracy_score(y_test, y_pred_bow))
print(confusion_matrix(y_test, y_pred_bow))
print(classification_report(y_test, y_pred_bow))

BoW Accuracy: 0.9847533632286996
[[966   0]
 [ 17 132]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       966
           1       1.00      0.89      0.94       149

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.97      1115
weighted avg       0.99      0.98      0.98      1115



In [275]:
new_mail = ["Congratulations! You won a lottery. Claim now."]  # list of new mails

In [276]:
# Step 1: Transform new mail using the trained BoW vectorizer
new_bow = bow.transform(new_mail)

# Step 2: Predict
pred_bow = model_bow.predict(new_bow)

# Step 3: Print result
print("BoW Prediction:", "Spam" if pred_bow[0]==1 else "Ham")

BoW Prediction: Ham


In [288]:
new_mails= ["Hey, are we meeting tomorrow for lunch?", "Congratulations ! You won a lottery. Claim now!", "Earn $5000 per week from home."]

In [289]:
new_bow = bow.transform(new_mails)
pred_bow = model_bow.predict(new_bow)

for mail, pred in zip(new_mails, pred_bow):
    print("Bow prediction:", "Spam" if pred==1 else "Ham", "| Mail:", mail)

Bow prediction: Ham | Mail: Hey, are we meeting tomorrow for lunch?
Bow prediction: Ham | Mail: Congratulations ! You won a lottery. Claim now!
Bow prediction: Ham | Mail: Earn $5000 per week from home.


### Tf-idf

In [277]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=3000
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

In [278]:
model_tfidf = LogisticRegression(max_iter=1000)
model_tfidf.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [279]:
y_pred_tfidf = model_tfidf.predict(X_test_tfidf)

print("TF-IDF Accuracy:", accuracy_score(y_test, y_pred_tfidf))
print(confusion_matrix(y_test, y_pred_tfidf))
print(classification_report(y_test, y_pred_tfidf))

TF-IDF Accuracy: 0.9748878923766816
[[966   0]
 [ 28 121]]
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       966
           1       1.00      0.81      0.90       149

    accuracy                           0.97      1115
   macro avg       0.99      0.91      0.94      1115
weighted avg       0.98      0.97      0.97      1115



In [280]:
# Step 1: Transform using TF-IDF vectorizer
new_tfidf = tfidf.transform(new_mail)

# Step 2: Predict
pred_tfidf = model_tfidf.predict(new_tfidf)

# Step 3: Print result
print("TF-IDF Prediction:", "Spam" if pred_tfidf[0]==1 else "Ham")

TF-IDF Prediction: Spam


### Word2-vec

In [281]:
def tokenize(text):
    tokens = word_tokenize(text.lower())
    tokens = [w for w in tokens if w.isalpha()]
    tokens = [w for w in tokens if w not in stopwords.words('english')]
    return tokens

X_train_tokens = X_train.apply(tokenize)
X_test_tokens = X_test.apply(tokenize)

In [282]:
from gensim.models import Word2Vec

w2v_model = Word2Vec(
    sentences=X_train_tokens,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

In [283]:
def vectorize_sentence(tokens, model):
    vectors = [model.wv[word] for word in tokens if word in model.wv]
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    return np.mean(vectors, axis=0)

X_train_w2v = np.array([vectorize_sentence(s, w2v_model) for s in X_train_tokens])
X_test_w2v = np.array([vectorize_sentence(s, w2v_model) for s in X_test_tokens])

In [284]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_w2v = scaler.fit_transform(X_train_w2v)
X_test_w2v = scaler.transform(X_test_w2v)

In [285]:
model_w2v = LogisticRegression(max_iter=1000)
model_w2v.fit(X_train_w2v, y_train)

LogisticRegression(max_iter=1000)

In [286]:
y_pred_w2v = model_w2v.predict(X_test_w2v)

print("Word2Vec Accuracy:", accuracy_score(y_test, y_pred_w2v))
print(confusion_matrix(y_test, y_pred_w2v))
print(classification_report(y_test, y_pred_w2v))

Word2Vec Accuracy: 0.9219730941704036
[[946  20]
 [ 67  82]]
              precision    recall  f1-score   support

           0       0.93      0.98      0.96       966
           1       0.80      0.55      0.65       149

    accuracy                           0.92      1115
   macro avg       0.87      0.76      0.80      1115
weighted avg       0.92      0.92      0.92      1115



In [287]:
# Step 1: Tokenize
new_tokens = [tokenize(mail) for mail in new_mail]

# Step 2: Convert to average Word2Vec vector
new_w2v = np.array([vectorize_sentence(tokens, w2v_model) for tokens in new_tokens])

# Step 3: Scale
new_w2v = scaler.transform(new_w2v)

# Step 4: Predict
pred_w2v = model_w2v.predict(new_w2v)

# Step 5: Print
print("Word2Vec Prediction:", "Spam" if pred_w2v[0]==1 else "Ham")

Word2Vec Prediction: Spam
